name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test1_multiplesOf3_notNullAndSize
      id: test1_multiplesof3_notnullandsize
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test1_multiplesOf3_notNullAndSize
        setup-command: ''
        command: mvn -B -q -Dtest=NumberListTest#multiplesOf3_notNullAndSize test
        timeout: 1
        max-score: 3
    - name: Test2_multiplesOf3_firstAndLastValues
      id: test2_multiplesof3_firstandlastvalues
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test2_multiplesOf3_firstAndLastValues
        setup-command: ''
        command: mvn -B -q -Dtest=NumberListTest#multiplesOf3_firstAndLastValues test
        timeout: 1
        max-score: 3
    - name: Test3_multiplesOf3_fullSequenceCorrect
      id: test3_multiplesof3_fullsequencecorrect
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test3_multiplesOf3_fullSequenceCorrect
        setup-command: ''
        command: mvn -B -q -Dtest=NumberListTest#multiplesOf3_fullSequenceCorrect
          test
        timeout: 1
        max-score: 4
    - name: Test4_toString_notNullAndHasNewlines
      id: test4_tostring_notnullandhasnewlines
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test4_toString_notNullAndHasNewlines
        setup-command: ''
        command: mvn -B -q -Dtest=NumberListTest#toString_notNullAndHasNewlines test
        timeout: 1
        max-score: 3
    - name: Test5_removeEvens_removesAllEvenNumbers
      id: test5_removeevens_removesallevennumbers
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test5_removeEvens_removesAllEvenNumbers
        setup-command: ''
        command: mvn -B -q -Dtest=NumberListTest#removeEvens_removesAllEvenNumbers
          test
        timeout: 1
        max-score: 2
    - name: Test6_removeEvens_resultsInCorrectOddSequence
      id: test6_removeevens_resultsincorrectoddsequence
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test6_removeEvens_resultsInCorrectOddSequence
        setup-command: ''
        command: mvn -B -q -Dtest=NumberListTest#removeEvens_resultsInCorrectOddSequence
          test
        timeout: 1
        max-score: 2
    - name: Test7_toString_containsAllNumbersInOrder
      id: test7_tostring_containsallnumbersinorder
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test7_toString_containsAllNumbersInOrder
        setup-command: ''
        command: mvn -B -q -Dtest=NumberListTest#toString_containsAllNumbersInOrder
          test
        timeout: 1
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1_MULTIPLESOF3_NOTNULLANDSIZE_RESULTS: "${{steps.test1_multiplesof3_notnullandsize.outputs.result}}"
        TEST2_MULTIPLESOF3_FIRSTANDLASTVALUES_RESULTS: "${{steps.test2_multiplesof3_firstandlastvalues.outputs.result}}"
        TEST3_MULTIPLESOF3_FULLSEQUENCECORRECT_RESULTS: "${{steps.test3_multiplesof3_fullsequencecorrect.outputs.result}}"
        TEST4_TOSTRING_NOTNULLANDHASNEWLINES_RESULTS: "${{steps.test4_tostring_notnullandhasnewlines.outputs.result}}"
        TEST5_REMOVEEVENS_REMOVESALLEVENNUMBERS_RESULTS: "${{steps.test5_removeevens_removesallevennumbers.outputs.result}}"
        TEST6_REMOVEEVENS_RESULTSINCORRECTODDSEQUENCE_RESULTS: "${{steps.test6_removeevens_resultsincorrectoddsequence.outputs.result}}"
        TEST7_TOSTRING_CONTAINSALLNUMBERSINORDER_RESULTS: "${{steps.test7_tostring_containsallnumbersinorder.outputs.result}}"
      with:
        runners: test1_multiplesof3_notnullandsize,test2_multiplesof3_firstandlastvalues,test3_multiplesof3_fullsequencecorrect,test4_tostring_notnullandhasnewlines,test5_removeevens_removesallevennumbers,test6_removeevens_resultsincorrectoddsequence,test7_tostring_containsallnumbersinorder
